version: '3.7'
services:
  Inventory:
    container_name: Inventory
    restart: unless-stopped
    image: nerodacles/pharmacyapi:latest
    build:
      context: ./
      target: dev
    networks:
      inventory:
        ipv4_address: 172.20.0.4
    volumes:
      - .:/src
      # - /home/nero/PharmacyApp/PharmacyFiles/Images:/src/uploads
    command: npm start
    ports:
      - "8087:3000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*

networks:
  inventory:
    external: true